// <auto-generated />
using System;
using Baion.Orchestrator.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Baion.Orchestrator.Persistence.Migrations
{
    [DbContext(typeof(BaionDbContext))]
    [Migration("20260901170613_AddIdentityTables")]
    partial class AddIdentityTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.Metric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("captured_at");

                    b.Property<int>("CpuCoreCount")
                        .HasColumnType("int")
                        .HasColumnName("cpu_core_count");

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("float")
                        .HasColumnName("cpu_usage_percent");

                    b.Property<double?>("LoadAverage1m")
                        .HasColumnType("float")
                        .HasColumnName("load_average1m");

                    b.Property<long>("MemoryAvailableBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("memory_available_bytes");

                    b.Property<long>("MemoryTotalBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("memory_total_bytes");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("server_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_metrics");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("ServerId", "CapturedAt")
                        .HasDatabaseName("ix_metrics_server_id_captured_at");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ServerId", "CapturedAt"));

                    b.HasIndex("TenantId", "CapturedAt")
                        .HasDatabaseName("ix_metrics_tenant_id_captured_at");

                    b.ToTable("metrics");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_tenant_id_normalized_name");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.ScheduledTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cron_expression");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_run_at");

                    b.Property<int>("Mode")
                        .HasColumnType("int")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("NextRunAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("next_run_at");

                    b.Property<Guid?>("ScriptChainId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("script_chain_id");

                    b.Property<Guid?>("ScriptId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("script_id");

                    b.Property<Guid?>("ServerGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("server_group_id");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("server_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_scheduled_tasks");

                    b.HasIndex("ScriptChainId")
                        .HasDatabaseName("ix_scheduled_tasks_script_chain_id");

                    b.HasIndex("ScriptId")
                        .HasDatabaseName("ix_scheduled_tasks_script_id");

                    b.HasIndex("ServerGroupId")
                        .HasDatabaseName("ix_scheduled_tasks_server_group_id");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_scheduled_tasks_server_id");

                    b.HasIndex("IsEnabled", "NextRunAt")
                        .HasDatabaseName("ix_scheduled_tasks_is_enabled_next_run_at");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_scheduled_tasks_tenant_id_name");

                    b.ToTable("scheduled_tasks", t =>
                        {
                            t.HasCheckConstraint("ck_scheduled_tasks_payload", "(CASE WHEN [script_id] IS NULL THEN 0 ELSE 1 END + CASE WHEN [script_chain_id] IS NULL THEN 0 ELSE 1 END) = 1");

                            t.HasCheckConstraint("ck_scheduled_tasks_target", "(CASE WHEN [server_id] IS NULL THEN 0 ELSE 1 END + CASE WHEN [server_group_id] IS NULL THEN 0 ELSE 1 END) = 1");
                        });
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.Script", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .HasColumnName("checksum")
                        .IsFixedLength();

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<int>("DefaultTimeoutSeconds")
                        .HasColumnType("int")
                        .HasColumnName("default_timeout_seconds");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("Runtime")
                        .HasColumnType("int")
                        .HasColumnName("runtime");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_scripts");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_scripts_tenant_id_name");

                    b.ToTable("scripts");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.ScriptChain", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_script_chains");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_script_chains_tenant_id_name");

                    b.ToTable("script_chains");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.ScriptChainStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<int>("FailurePolicy")
                        .HasColumnType("int")
                        .HasColumnName("failure_policy");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("step_order");

                    b.Property<Guid>("ScriptChainId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("script_chain_id");

                    b.Property<Guid>("ScriptId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("script_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("TimeoutSecondsOverride")
                        .HasColumnType("int")
                        .HasColumnName("timeout_seconds_override");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_script_chain_steps");

                    b.HasIndex("ScriptId")
                        .HasDatabaseName("ix_script_chain_steps_script_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_script_chain_steps_tenant_id");

                    b.HasIndex("ScriptChainId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_script_chain_steps_script_chain_id_step_order");

                    b.ToTable("script_chain_steps");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.ScriptExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChainRunId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chain_run_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("error_message");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("int")
                        .HasColumnName("exit_code");

                    b.Property<int>("Mode")
                        .HasColumnType("int")
                        .HasColumnName("mode");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("queued_at");

                    b.Property<Guid?>("ScriptChainStepId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("script_chain_step_id");

                    b.Property<Guid>("ScriptId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("script_id");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("server_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("StdErr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("std_err");

                    b.Property<string>("StdOut")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("std_out");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_script_executions");

                    b.HasIndex("ChainRunId")
                        .HasDatabaseName("ix_script_executions_chain_run_id")
                        .HasFilter("[chain_run_id] IS NOT NULL");

                    b.HasIndex("ScriptChainStepId")
                        .HasDatabaseName("ix_script_executions_script_chain_step_id");

                    b.HasIndex("ScriptId")
                        .HasDatabaseName("ix_script_executions_script_id");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_script_executions_server_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_script_executions_tenant_id_status");

                    b.HasIndex("TenantId", "ServerId", "QueuedAt")
                        .HasDatabaseName("ix_script_executions_tenant_id_server_id_queued_at");

                    b.ToTable("script_executions");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("agent_version");

                    b.Property<DateTimeOffset?>("ConnectedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("connected_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hostname");

                    b.Property<int>("Kind")
                        .HasColumnType("int")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_seen_at");

                    b.Property<int>("MaxConcurrentExecutions")
                        .HasColumnType("int")
                        .HasColumnName("max_concurrent_executions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("OrchestratorInstanceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("orchestrator_instance_id");

                    b.Property<int>("Platform")
                        .HasColumnType("int")
                        .HasColumnName("platform");

                    b.Property<string>("RuntimeIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("runtime_identifier");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_servers");

                    b.HasIndex("OrchestratorInstanceId")
                        .HasDatabaseName("ix_servers_orchestrator_instance_id")
                        .HasFilter("[orchestrator_instance_id] IS NOT NULL");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_servers_tenant_id_name");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_servers_tenant_id_status");

                    b.ToTable("servers");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.ServerGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_server_groups");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_server_groups_tenant_id_name");

                    b.ToTable("server_groups");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.ServerGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ServerGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("server_group_id");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("server_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_server_group_members");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_server_group_members_server_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_server_group_members_tenant_id");

                    b.HasIndex("ServerGroupId", "ServerId")
                        .IsUnique()
                        .HasDatabaseName("ix_server_group_members_server_group_id_server_id");

                    b.ToTable("server_group_members");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalTenantId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("external_tenant_id");

                    b.Property<int>("IdentityMode")
                        .HasColumnType("int")
                        .HasColumnName("identity_mode");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("ExternalTenantId")
                        .HasDatabaseName("ix_tenants_external_tenant_id")
                        .HasFilter("[external_tenant_id] IS NOT NULL");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockoutEndsAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("lockout_ends_at");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("security_stamp");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_normalized_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_roles_tenant_id");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_roles_user_id_role_id");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.Metric", b =>
                {
                    b.HasOne("Baion.Orchestrator.Models.Entities.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_metrics_servers_server_id");

                    b.OwnsMany("Baion.Orchestrator.Models.Entities.MetricDisk", "Disks", b1 =>
                        {
                            b1.Property<long>("MetricId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<long>("AvailableBytes")
                                .HasJsonPropertyName("availableBytes");

                            b1.Property<string>("MountPoint")
                                .IsRequired()
                                .HasJsonPropertyName("mountPoint");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasJsonPropertyName("name");

                            b1.Property<long>("TotalBytes")
                                .HasJsonPropertyName("totalBytes");

                            b1.HasKey("MetricId", "__synthesizedOrdinal");

                            b1.ToTable("metrics");

                            b1
                                .ToJson("disks")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("MetricId");
                        });

                    b.Navigation("Disks");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.Role", b =>
                {
                    b.HasOne("Baion.Orchestrator.Models.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_roles_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.ScheduledTask", b =>
                {
                    b.HasOne("Baion.Orchestrator.Models.Entities.ScriptChain", "ScriptChain")
                        .WithMany()
                        .HasForeignKey("ScriptChainId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_scheduled_tasks_script_chains_script_chain_id");

                    b.HasOne("Baion.Orchestrator.Models.Entities.Script", "Script")
                        .WithMany()
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_scheduled_tasks_scripts_script_id");

                    b.HasOne("Baion.Orchestrator.Models.Entities.ServerGroup", "ServerGroup")
                        .WithMany()
                        .HasForeignKey("ServerGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_scheduled_tasks_server_groups_server_group_id");

                    b.HasOne("Baion.Orchestrator.Models.Entities.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_scheduled_tasks_servers_server_id");

                    b.HasOne("Baion.Orchestrator.Models.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_scheduled_tasks_tenants_tenant_id");

                    b.Navigation("Script");

                    b.Navigation("ScriptChain");

                    b.Navigation("Server");

                    b.Navigation("ServerGroup");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.Script", b =>
                {
                    b.HasOne("Baion.Orchestrator.Models.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_scripts_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.ScriptChain", b =>
                {
                    b.HasOne("Baion.Orchestrator.Models.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_script_chains_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.ScriptChainStep", b =>
                {
                    b.HasOne("Baion.Orchestrator.Models.Entities.ScriptChain", "ScriptChain")
                        .WithMany("Steps")
                        .HasForeignKey("ScriptChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_script_chain_steps_script_chains_script_chain_id");

                    b.HasOne("Baion.Orchestrator.Models.Entities.Script", "Script")
                        .WithMany()
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_script_chain_steps_scripts_script_id");

                    b.HasOne("Baion.Orchestrator.Models.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_script_chain_steps_tenants_tenant_id");

                    b.Navigation("Script");

                    b.Navigation("ScriptChain");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.ScriptExecution", b =>
                {
                    b.HasOne("Baion.Orchestrator.Models.Entities.ScriptChainStep", "ScriptChainStep")
                        .WithMany()
                        .HasForeignKey("ScriptChainStepId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_script_executions_script_chain_steps_script_chain_step_id");

                    b.HasOne("Baion.Orchestrator.Models.Entities.Script", "Script")
                        .WithMany("Executions")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_script_executions_scripts_script_id");

                    b.HasOne("Baion.Orchestrator.Models.Entities.Server", "Server")
                        .WithMany("Executions")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_script_executions_servers_server_id");

                    b.HasOne("Baion.Orchestrator.Models.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_script_executions_tenants_tenant_id");

                    b.Navigation("Script");

                    b.Navigation("ScriptChainStep");

                    b.Navigation("Server");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.Server", b =>
                {
                    b.HasOne("Baion.Orchestrator.Models.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_servers_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.ServerGroup", b =>
                {
                    b.HasOne("Baion.Orchestrator.Models.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_server_groups_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.ServerGroupMember", b =>
                {
                    b.HasOne("Baion.Orchestrator.Models.Entities.ServerGroup", "ServerGroup")
                        .WithMany("Members")
                        .HasForeignKey("ServerGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_server_group_members_server_groups_server_group_id");

                    b.HasOne("Baion.Orchestrator.Models.Entities.Server", "Server")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_server_group_members_servers_server_id");

                    b.HasOne("Baion.Orchestrator.Models.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_server_group_members_tenants_tenant_id");

                    b.Navigation("Server");

                    b.Navigation("ServerGroup");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.User", b =>
                {
                    b.HasOne("Baion.Orchestrator.Models.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.UserRole", b =>
                {
                    b.HasOne("Baion.Orchestrator.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Baion.Orchestrator.Models.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_tenants_tenant_id");

                    b.HasOne("Baion.Orchestrator.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.Script", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.ScriptChain", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.Server", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("GroupMemberships");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.ServerGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Baion.Orchestrator.Models.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
