<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Baion.TestSupport\Baion.TestSupport.csproj" />
    <ProjectReference Include="..\..\src\Orchestrator\Baion.Orchestrator.Identity\Baion.Orchestrator.Identity.csproj" />
  </ItemGroup>

</Project>
